import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { prisma } from '@/lib/database';
import { getSignedImageUrl, extractKeyFromR2Url } from '@/lib/r2-signed-urls';
import JSZip from 'jszip';

/**
 * Server-side ZIP generation endpoint
 * Generates a complete ZIP file with all images and metadata on the server
 * This avoids CORS issues when downloading from R2
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ designId: string }> }
) {
  try {
    const { designId } = await params;

    console.log('\n📦 === SERVER-SIDE ZIP GENERATION ===');
    console.log('Design ID:', designId);

    // Authenticate user
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Fetch design with outputs
    const design = await prisma.design.findUnique({
      where: { id: designId },
      include: {
        outputs: true,
      },
    });

    if (!design) {
      return NextResponse.json(
        { error: 'Design not found' },
        { status: 404 }
      );
    }

    // Check ownership
    if (design.userId !== user.id) {
      return NextResponse.json(
        { error: 'Unauthorized to download this design' },
        { status: 403 }
      );
    }

    console.log(`✅ Found design with ${design.outputs?.length || 0} outputs`);

    // Create ZIP file
    const zip = new JSZip();
    const folderName = `design-${design.id.slice(0, 8)}`;
    const folder = zip.folder(folderName);

    if (!folder) {
      throw new Error('Failed to create ZIP folder');
    }

    // Add metadata
    const metadata = {
      id: design.id,
      title: design.title,
      description: design.description,
      status: design.status,
      roomType: design.roomType,
      size: design.size,
      style: design.style,
      budget: design.budget,
      colorScheme: design.colorScheme,
      customRequirements: design.customRequirements,
      createdAt: design.createdAt,
      updatedAt: design.updatedAt,
      generationNumber: design.generationNumber,
      outputCount: design.outputs?.length || 0,
    };

    folder.file('metadata.json', JSON.stringify(metadata, null, 2));

    // Add ROI analysis if available
    if (design.roiNotes) {
      folder.file('roi-analysis.txt', design.roiNotes);

      const markdownContent = `# ROI Analysis for Design ${design.id.slice(0, 8)}

## Design Details
- **Room Type:** ${design.roomType}
- **Room Size:** ${design.size}
- **Style:** ${design.style}
- **Budget:** ${design.budget ? `$${design.budget}` : 'Not specified'}
- **Created:** ${new Date(design.createdAt).toLocaleDateString()}

## Financial Analysis

${design.roiNotes}

---
*Generated by InnDesign AI*
`;
      folder.file('roi-analysis.md', markdownContent);
    }

    // Process images - fetch them server-side
    console.log('\n📥 Fetching images server-side...');
    const imagesFolder = folder.folder('images');
    let successCount = 0;
    let failCount = 0;

    if (imagesFolder && design.outputs) {
      for (let i = 0; i < design.outputs.length; i++) {
        const output = design.outputs[i];
        console.log(`\n[${i + 1}/${design.outputs.length}] Processing: ${output.variationName || `image-${i + 1}`}`);

        if (!output.outputImageUrl) {
          console.warn('  ⚠️ Skipping - no URL provided');
          failCount++;
          continue;
        }

        try {
          let blob: Blob;
          let extension = 'png';

          // Check if it's a base64 data URL
          if (output.outputImageUrl.startsWith('data:image')) {
            console.log('  📸 Type: Base64 data URL');

            const matches = output.outputImageUrl.match(/^data:image\/([a-zA-Z]+);base64,(.+)$/);
            if (matches) {
              extension = matches[1];
              const base64Data = matches[2];

              // Convert base64 to buffer
              const buffer = Buffer.from(base64Data, 'base64');
              blob = new Blob([buffer], { type: `image/${extension}` });
              console.log(`  ✅ Converted to blob (${(blob.size / 1024).toFixed(2)} KB)`);
            } else {
              console.error('  ❌ Failed to parse base64 data URL');
              failCount++;
              continue;
            }
          }
          // R2 URL - generate fresh signed URL and fetch server-side
          else if (output.outputImageUrl.includes('r2.cloudflarestorage.com') ||
                   output.outputImageUrl.includes('cloudflare') ||
                   output.outputImageUrl.includes('.r2.dev')) {
            console.log('  ☁️ Type: R2 URL - fetching server-side');

            const key = extractKeyFromR2Url(output.outputImageUrl);

            if (!key) {
              console.error('  ❌ Failed to extract key from R2 URL');
              failCount++;
              continue;
            }

            console.log(`  🔑 Extracted key: ${key}`);

            // Generate fresh signed URL (10 minute expiry for server-side fetch)
            const signedUrl = await getSignedImageUrl(key, 600);

            if (!signedUrl) {
              console.error('  ❌ Failed to generate signed URL');
              failCount++;
              continue;
            }

            console.log('  📡 Fetching from R2...');

            // Try signed URL first
            let response = await fetch(signedUrl);

            // If signed URL fails, try original public URL as fallback
            if (!response.ok) {
              console.warn(`  ⚠️ Signed URL failed (${response.status}), trying public URL directly...`);
              response = await fetch(output.outputImageUrl);

              if (!response.ok) {
                console.error(`  ❌ Failed to fetch: ${response.status} ${response.statusText}`);
                failCount++;
                continue;
              }
              console.log('  ✅ Public URL worked!');
            }

            const arrayBuffer = await response.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);

            // Get extension from content type or default to png
            const contentType = response.headers.get('content-type') || 'image/png';
            extension = contentType.split('/')[1] || 'png';

            blob = new Blob([buffer], { type: contentType });
            console.log(`  ✅ Downloaded (${(blob.size / 1024).toFixed(2)} KB)`);
          }
          // External URL
          else {
            console.log('  🌐 Type: External URL');

            const response = await fetch(output.outputImageUrl);

            if (!response.ok) {
              console.error(`  ❌ Failed to fetch: ${response.status}`);
              failCount++;
              continue;
            }

            const arrayBuffer = await response.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);

            const contentType = response.headers.get('content-type') || 'image/png';
            extension = contentType.split('/')[1] || 'png';

            blob = new Blob([buffer], { type: contentType });
            console.log(`  ✅ Downloaded (${(blob.size / 1024).toFixed(2)} KB)`);
          }

          // Add to ZIP
          const filename = `${output.variationName || `image-${i + 1}`}.${extension}`;
          imagesFolder.file(filename, await blob.arrayBuffer());
          successCount++;
          console.log(`  ✅ Added to ZIP: ${filename}`);

        } catch (error) {
          failCount++;
          console.error('  ❌ Failed to process image:', error);
        }
      }
    }

    console.log('\n📊 Download Summary:');
    console.log(`  ✅ Successful: ${successCount}/${design.outputs?.length || 0}`);
    console.log(`  ❌ Failed: ${failCount}/${design.outputs?.length || 0}`);

    // Add README
    const readme = `# Design Package: ${design.title || design.id.slice(0, 8)}

This package contains all generated design outputs and analysis.

## Contents

- \`metadata.json\` - Design configuration and metadata
- \`roi-analysis.txt\` - Financial analysis and ROI projections (if available)
- \`roi-analysis.md\` - Formatted ROI analysis (if available)
- \`images/\` - All generated design images (${successCount} images)

## Design Information

**Description:** ${design.description}

**Room Details:**
- Type: ${design.roomType}
- Size: ${design.size}
- Style: ${design.style}

**Generated:** ${new Date(design.createdAt).toLocaleString()}

---
Generated by InnDesign AI
`;

    folder.file('README.md', readme);

    console.log('🗜️ Generating ZIP file...');

    // Generate ZIP file
    const zipBuffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: 'DEFLATE',
      compressionOptions: { level: 9 }
    });

    console.log(`✅ ZIP generated (${(zipBuffer.length / 1024 / 1024).toFixed(2)} MB)`);
    console.log('📦 === ZIP GENERATION COMPLETE ===\n');

    // Return ZIP file - convert Buffer to Uint8Array for NextResponse
    return new NextResponse(new Uint8Array(zipBuffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${folderName}-complete.zip"`,
        'Content-Length': zipBuffer.length.toString(),
      },
    });

  } catch (error) {
    console.error('\n❌ === ZIP GENERATION ERROR ===');
    console.error('Error:', error);
    console.error('==============================\n');

    return NextResponse.json(
      {
        error: 'Failed to generate ZIP file',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}
